/**
 * One zod schema per entity, shared client and server (CLAUDE.md section 2).
 *
 * The server actions parse untrusted input with these; the form validates the
 * same shape before it ever calls one, so the two can never disagree about what
 * a valid expense is.
 */

import { z } from 'zod'

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/

const isoDate = z
  .string()
  .regex(ISO_DATE, 'Date must be YYYY-MM-DD')
  .refine((value) => !Number.isNaN(Date.parse(value)), 'That is not a real date')

/** Trim, then treat an empty string as absent. Forms hand back '' , not null. */
const optionalText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .transform((value) => (value === '' ? null : value))
    .nullable()
    .default(null)

const optionalUuid = z
  .union([z.uuid(), z.literal('')])
  .transform((value) => (value === '' ? null : value))
  .nullable()
  .default(null)

/**
 * Money is a whole number of minor units and is never zero: an expense of
 * nothing is a mistake, not a record. Negative is allowed and meaningful —
 * a refund, or a part sold on.
 */
const minorAmount = z
  .number()
  .int('Amount must be a whole number of minor units')
  .refine((value) => Number.isSafeInteger(value), 'Amount is out of range')
  .refine((value) => value !== 0, 'Enter an amount')

export const expenseWriteSchema = z
  .object({
    /**
     * Generated by the client so the optimistic row and the stored row are the
     * same row. A duplicate id is rejected by the primary key, which is the
     * behaviour we want if a submit is somehow replayed.
     */
    id: z.uuid(),
    occurred_on: isoDate,
    amount: minorAmount,
    currency: z.string().length(3).toUpperCase(),
    category_id: optionalUuid,
    vehicle_id: optionalUuid,
    bucket: z.enum(['life', 'car_running', 'car_project']),
    counts_toward_budget: z.boolean(),
    amortize_months: z.number().int().min(1).max(120),
    merchant: optionalText(160),
    note: optionalText(2000),
    odometer_km: z.number().int().min(0).max(9_999_999).nullable().default(null),
  })
  .refine(
    (value) => (value.bucket === 'life' ? value.vehicle_id === null : value.vehicle_id !== null),
    {
      message: 'A car bucket needs a vehicle, and life spend cannot have one',
      path: ['bucket'],
    },
  )
  .refine((value) => value.odometer_km === null || value.vehicle_id !== null, {
    message: 'An odometer reading needs a vehicle',
    path: ['odometer_km'],
  })

export type ExpenseWrite = z.infer<typeof expenseWriteSchema>

export const expenseIdSchema = z.uuid()

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

/** Six characters of hex with a hash. Swatches are offered; typing is allowed. */
const hexColour = z
  .string()
  .trim()
  .regex(/^#[0-9a-fA-F]{6}$/, 'Colour must be a six-digit hex like #A95031')
  .transform((value) => value.toUpperCase())

export const categoryWriteSchema = z.object({
  id: z.uuid(),
  name: z.string().trim().min(1, 'Name the category').max(60),
  icon: z.string().trim().min(1).max(60),
  colour_hex: hexColour,
  default_bucket: z.enum(['life', 'car_running', 'car_project']),
  default_counts_toward_budget: z.boolean(),
  sort_order: z.number().int().nullable().default(null),
})

export type CategoryWrite = z.infer<typeof categoryWriteSchema>

export const categoryArchiveSchema = z.object({
  id: z.uuid(),
  archived: z.boolean(),
})
