/**
 * The mod-plan schema. One zod schema per entity, shared client and server
 * (CLAUDE.md section 2); the client imports it as a type only, for the bundle
 * reason recorded in `lib/expenses/schema.ts`.
 */

import { z } from 'zod'

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/

const isoDate = z
  .string()
  .regex(ISO_DATE, 'Date must be YYYY-MM-DD')
  .refine((value) => !Number.isNaN(Date.parse(value)), 'That is not a real date')

const optionalText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .transform((value) => (value === '' ? null : value))
    .nullable()
    .default(null)

/** Money is a whole number of minor units. An estimate of nothing is no estimate. */
const optionalMinor = z
  .number()
  .int('Amount must be a whole number of minor units')
  .min(0, 'An estimate cannot be negative')
  .refine((value) => Number.isSafeInteger(value), 'Amount is out of range')
  .nullable()
  .default(null)

/**
 * A part link. `javascript:` and `data:` URLs are the reason this is not just
 * `z.url()`: these strings end up in an `href` on a page the user trusts.
 */
const modLink = z.object({
  label: z.string().trim().min(1, 'Give the link a label').max(80),
  url: z
    .string()
    .trim()
    .max(2000)
    .refine((value) => {
      try {
        const parsed = new URL(value)
        return parsed.protocol === 'http:' || parsed.protocol === 'https:'
      } catch {
        return false
      }
    }, 'A link needs to start with http:// or https://'),
})

export const MOD_STATUSES = [
  'dreaming',
  'researching',
  'saving',
  'ordered',
  'installed',
  'abandoned',
] as const

export const modWriteSchema = z
  .object({
    /** Generated by the client, so the optimistic card and the row are one row. */
    id: z.uuid(),
    vehicle_id: z.uuid(),
    title: z.string().trim().min(1, 'Give the mod a name').max(120),
    description: optionalText(2000),
    status: z.enum(MOD_STATUSES),
    priority: z.enum(['needed', 'next_up', 'someday', 'dreaming']),
    est_cost_min: optionalMinor,
    est_cost_max: optionalMinor,
    currency: z.string().length(3).toUpperCase(),
    target_date: isoDate.nullable().default(null),
    links: z.array(modLink).max(12, 'Twelve links is plenty').default([]),
    notes: optionalText(4000),
    /** Only ever set by the board or the install flow; null clears the stamp. */
    installed_on: isoDate.nullable().default(null),
  })
  .refine(
    (value) =>
      value.est_cost_min === null ||
      value.est_cost_max === null ||
      value.est_cost_min <= value.est_cost_max,
    { message: 'The low end of the estimate is above the high end', path: ['est_cost_max'] },
  )

export type ModWrite = z.infer<typeof modWriteSchema>

export const modIdSchema = z.uuid()

export const modArchiveSchema = z.object({
  id: z.uuid(),
  archived: z.boolean(),
})

/**
 * The dependency set of one mod. Self-dependency is refused here as well as by
 * the check constraint, because the constraint's message is a constraint name
 * and this one is a sentence. Cycles are a different check and live in
 * `lib/mods/graph.ts` — they need the rest of the board to see them.
 */
export const modDependenciesSchema = z.object({
  mod_plan_id: z.uuid(),
  depends_on: z
    .array(z.uuid())
    .max(20, 'Twenty dependencies is more plan than anyone has')
    .default([])
    .transform((ids) => [...new Set(ids)]),
})

export type ModDependencies = z.infer<typeof modDependenciesSchema>

/** One board drag, as the set of rows whose position changed. */
export const modMovesSchema = z.object({
  vehicle_id: z.uuid(),
  today: isoDate,
  moves: z
    .array(
      z.object({
        id: z.uuid(),
        status: z.enum(MOD_STATUSES),
        board_order: z.number().int().min(0).max(10_000),
      }),
    )
    .min(1)
    .max(400),
})
