/**
 * One zod schema per entity, shared client and server (CLAUDE.md section 2).
 *
 * As with the expense schema, the browser imports these as **types only** — zod
 * is around seventy kilobytes gzipped and the route budget is forty for
 * everything (AUTOPILOT-NOTES.md, Phase 2 assumption 1). The server actions parse
 * with them, so they are still the only gate on a write.
 */

import { z } from 'zod'
import { FUEL_TYPES, TRANSMISSIONS } from '@/lib/vehicles/types'

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/

const optionalIsoDate = z
  .union([z.string().regex(ISO_DATE, 'Date must be YYYY-MM-DD'), z.literal('')])
  .transform((value) => (value === '' ? null : value))
  .nullable()
  .default(null)

const optionalText = (max: number) =>
  z
    .string()
    .trim()
    .max(max)
    .transform((value) => (value === '' ? null : value))
    .nullable()
    .default(null)

const optionalHexColour = z
  .union([
    z
      .string()
      .trim()
      .regex(/^#[0-9a-fA-F]{6}$/, 'Colour must be a six-digit hex like #A95031')
      .transform((value) => value.toUpperCase()),
    z.literal(''),
  ])
  .transform((value) => (value === '' ? null : value))
  .nullable()
  .default(null)

const optionalEnum = <T extends readonly [string, ...string[]]>(values: T) =>
  z
    .union([z.enum(values), z.literal('')])
    .transform((value) => (value === '' ? null : value))
    .nullable()
    .default(null)

/** Money is a whole number of minor units. A price of nothing is "not recorded". */
const optionalMinorAmount = z
  .number()
  .int('Amount must be a whole number of minor units')
  .refine((value) => Number.isSafeInteger(value), 'Amount is out of range')
  .nullable()
  .default(null)

const odometer = z
  .number()
  .int('An odometer reading is a whole number of kilometres')
  .min(0, 'An odometer reading cannot be negative')
  .max(9_999_999, 'That reading is out of range')

/**
 * Everything except the nickname is optional and editable later. A car you have
 * not decided the trim of is still a car, and asking for it before it can be
 * skipped is how an onboarding flow gets abandoned.
 */
export const vehicleWriteSchema = z
  .object({
    /** Generated by the client, so the hero photo can be uploaded to its final
        path before the row exists. */
    id: z.uuid(),
    nickname: z.string().trim().min(1, 'Give it a name').max(60),
    make: optionalText(60),
    model: optionalText(60),
    year: z
      .number()
      .int()
      .min(1885, 'Cars did not exist yet')
      .max(2100, 'That is a long way off')
      .nullable()
      .default(null),
    trim: optionalText(60),
    plate: optionalText(20),
    colour_hex: optionalHexColour,
    fuel_type: optionalEnum(FUEL_TYPES),
    transmission: optionalEnum(TRANSMISSIONS),
    purchase_date: optionalIsoDate,
    purchase_price: optionalMinorAmount,
    currency: z.string().length(3).toUpperCase(),
    odometer_km: odometer,
    /** Where this owner's kilometres are measured from. Defaults to the reading
        entered at creation, which the form fills in for you. */
    purchase_odometer_km: odometer,
    hero_photo_path: optionalText(400),
  })
  .refine((value) => value.purchase_odometer_km <= value.odometer_km, {
    message: 'The reading at purchase cannot be higher than the current reading',
    path: ['purchase_odometer_km'],
  })

export type VehicleWrite = z.infer<typeof vehicleWriteSchema>

export const vehicleIdSchema = z.uuid()

export const vehicleArchiveSchema = z.object({
  id: z.uuid(),
  archived: z.boolean(),
})

/**
 * Selling.
 *
 * The date is required — a sale happened on a day, and `months_owned` is
 * measured to it rather than to today. The price is not: a car given away, or
 * scrapped, or handed to a relative for a figure nobody wants recorded, is still
 * a car that stopped being yours. A price of nothing means "not recorded", the
 * same as everywhere else in this schema, and the closing summary says so rather
 * than showing a zero.
 */
export const vehicleSellSchema = z.object({
  id: z.uuid(),
  sold_date: z.string().regex(ISO_DATE, 'Date must be YYYY-MM-DD'),
  sold_price: optionalMinorAmount,
  currency: z.string().length(3).toUpperCase(),
})

export type VehicleSell = z.infer<typeof vehicleSellSchema>

/** The view switcher writes its choice back to the profile on every change. */
export const defaultViewSchema = z.enum(['monthly', 'all_in', 'car_only'])
